[package]
name = "dfut"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
log = "0.4.21"
env_logger = "0.11.3"
lru = "0.12.3"

tonic = "0.11.0"
prost = "0.12.4"
tower-service = "0.3.2"
http = "0.2.11"

dfut-macro = { path = "../dfut-macro" }

[build-dependencies]
tonic-build = "0.11"
